version: '2'
services:

### MySQL ###############################################
  mysql:
    image: mysql:5.7
    container_name: THS_tools-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    labels:
      - "service-type:db-srv"
      - "environment:test"
      - "service-name:msqldatabase"
### gPAS ###
#      - "service-name:gpas"
### EPIX ###
#      - "service-name:epix"
### gICS ###
#      - "service-name:gics"


### EPIX ########################################
  EPIX:
    image: mosaicgreifswald/wildfly:18.0.1.Final-20191213
    container_name: THS_tools-epix
    links:
      - "mysql:mysqldb"
    ports:
      - "8081:8080"
      - "9991:9990"
    environment:
      WILDFLY_PASS: wildfly_password      
      JAVA_OPTS: '-server -Xms1G -Xmx6G -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=1G -XX:StringTableSize=1000003 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman' 
    depends_on:
      - mysql
    volumes:
      - .E-PIX/docker/standard/jboss:/entrypoint-jboss-batch
      - .E-PIX/docker/standard/deployments:/entrypoint-deployments
    labels:
      - "service-name:epix"
      - "service-type:app-srv"
      - "environment:test"
    entrypoint: /bin/bash
    command: -c "./wait-for-it.sh mysql:3306 -t 120 && ./run.sh"


### gPAS ########################################
  gPAS:
    image: mosaicgreifswald/wildfly:18.0.1.Final-20191213
    container_name: THS_tools-gpas
    links:
      - "mysql:mysqldb"
    ports:
      - "8082:8080"
      - "9992:9990"
    environment:
      WILDFLY_PASS: wildfly_password
      JAVA_OPTS: '-server -Xms1G -Xmx6G -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=1G -XX:StringTableSize=1000003 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman' 
    depends_on:
      - mysql
    volumes:
      - .gPAS/docker/standard/jboss:/entrypoint-jboss-batch
      - .gPAS/docker/standard/deployments:/entrypoint-deployments
    labels:
      - "service-name:gpas"
      - "service-type:app-srv"
      - "environment:test"
    entrypoint: /bin/bash
    command: -c "./wait-for-it.sh mysql:3306 -t 120 && ./run.sh"


### gICS ########################################
  gICS:
    image: mosaicgreifswald/wildfly:18.0.1.Final-20191213
    container_name: THS_tools-gics
    links:
      - "mysql:mysqldb"
    ports:
      - "8083:8080"
      - "9993:9990"
    environment:
      WILDFLY_PASS: wildfly_password
      JAVA_OPTS: '-server -Xms1G -Xmx6G -XX:MetaspaceSize=256M -XX:MaxMetaspaceSize=1G -XX:StringTableSize=1000003 -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman' 
    depends_on:
      - mysql
    volumes:
      - .gICS/docker/standard/jboss:/entrypoint-jboss-batch
      - .gICS/docker/standard/deployments:/entrypoint-deployments
    labels:
      - "service-name:gics"
      - "service-type:app-srv"
      - "environment:test"
    entrypoint: /bin/bash
    command: -c "./wait-for-it.sh mysql:3306 -t 120 && ./run.sh"
